// <auto-generated />
using System;
using CookbookAPI.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookbookAPI.Data.Migrations
{
    [DbContext(typeof(CookbookApiDbContext))]
    partial class CookbookApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CookbookAPI.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dessert"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Appetizer"
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Great recipe!",
                            CreatedAt = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7752),
                            RecipeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "My family loved it!",
                            CreatedAt = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7755),
                            RecipeId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Best cookies ever!",
                            CreatedAt = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7757),
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Simple and delicious!",
                            CreatedAt = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7759),
                            RecipeId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Favorites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 3,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipeId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecipeId = 1,
                            Stars = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            RecipeId = 1,
                            Stars = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            RecipeId = 2,
                            Stars = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            RecipeId = 3,
                            Stars = 5,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Difficulty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Ingredients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmissionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Difficulty = "Medium",
                            Duration = 30,
                            Ingredients = "Spaghetti, Ground beef, Tomato sauce, Onions, Garlic",
                            Instructions = "1. Cook spaghetti. 2. Make bolognese sauce. 3. Combine and serve.",
                            IsApproved = true,
                            Name = "Spaghetti Bolognese",
                            SubmissionDate = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7683)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Difficulty = "Easy",
                            Duration = 25,
                            Ingredients = "Flour, Sugar, Butter, Chocolate chips, Eggs",
                            Instructions = "1. Mix ingredients. 2. Form cookies. 3. Bake for 10-12 minutes.",
                            IsApproved = true,
                            Name = "Chocolate Chip Cookies",
                            SubmissionDate = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7690)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Difficulty = "Easy",
                            Duration = 10,
                            Ingredients = "Tomatoes, Fresh mozzarella, Basil, Olive oil, Balsamic vinegar",
                            Instructions = "1. Slice tomatoes and mozzarella. 2. Arrange on plate with basil. 3. Drizzle with olive oil and balsamic.",
                            IsApproved = true,
                            Name = "Caprese Salad",
                            SubmissionDate = new DateTime(2024, 10, 22, 16, 56, 46, 454, DateTimeKind.Utc).AddTicks(7693)
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user@mail.com",
                            IsBlocked = false,
                            Name = "Regular User",
                            Password = "AQAAAAIAAYagAAAAEFj3Md6jOZHs41jexBMgYBTIRw3CSGun/Jye/HT9dNnEPnnwl2RsPLOtIBle9jfzLA==",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "admin@mail.com",
                            IsBlocked = false,
                            Name = "Admin User",
                            Password = "AQAAAAIAAYagAAAAECz2jVq5vMy8f/Qdt5knwusT6jlM0CDoy/OAI5WdfAQJHc4GLuETLNQZd15LNyHssw==",
                            Role = 2
                        });
                });

            modelBuilder.Entity("CookbookAPI.Domain.Comment", b =>
                {
                    b.HasOne("CookbookAPI.Domain.Recipe", "Recipe")
                        .WithMany("Comments")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookbookAPI.Domain.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookbookAPI.Domain.Favorite", b =>
                {
                    b.HasOne("CookbookAPI.Domain.Recipe", "Recipe")
                        .WithMany("Favorites")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookbookAPI.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookbookAPI.Domain.Rating", b =>
                {
                    b.HasOne("CookbookAPI.Domain.Recipe", "Recipe")
                        .WithMany("Ratings")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookbookAPI.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CookbookAPI.Domain.Recipe", b =>
                {
                    b.HasOne("CookbookAPI.Domain.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CookbookAPI.Domain.User", null)
                        .WithMany("FavoriteRecipes")
                        .HasForeignKey("UserId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CookbookAPI.Domain.Category", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("CookbookAPI.Domain.Recipe", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("CookbookAPI.Domain.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("FavoriteRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
